#-------------------------------------------------------------------------------
# Name:        `AddressBase create table information for Oracle
# Purpose:     `This SQL code is to be used along side the Getting Started Guide
#								to setup the OS AddressBase tables within a database
# Created:     `19/02/2016
# Copyright:   `(c) Ordnance Survey 2016
# Licence:     `THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#               "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#               LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#               FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#               COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#               INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#               BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
#               OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
#               AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#               OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
#               THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE
#-------------------------------------------------------------------------------

-- Drop Existing Table if one currently exists--
DROP TABLE AddressBase CASCADE CONSTRAINTS;

-- Create Table for AddressBase CSV--
CREATE TABLE AddressBase (
UPRN NUMBER,
OS_ADDRESS_TOID VARCHAR2(20),
UDPRN NUMBER,
ORGANISATION_NAME VARCHAR2(60),
DEPARTMENT_NAME VARCHAR2(60),
PO_BOX_NUMBER VARCHAR2(6),
SUB_BUILDING_NAME VARCHAR2(30),
BUILDING_NAME VARCHAR2(50),
BUILDING_NUMBER NUMBER,
DEPENDENT_THOROUGHFARE VARCHAR2(80),
THOROUGHFARE VARCHAR2(80),
POST_TOWN VARCHAR2(30),
DOUBLE_DEPENDENT_LOCALITY VARCHAR2(35),
DEPENDENT_LOCALITY VARCHAR2(35),
POSTCODE VARCHAR2(8),
POSTCODE_TYPE VARCHAR2(1),
X_COORDINATE FLOAT,
Y_COORDINATE FLOAT,
LATITUDE FLOAT,
LONGITUDE FLOAT,
RPC NUMBER,
COUNTRY VARCHAR2(1),
CHANGE_TYPE VARCHAR2(1),
LA_START_DATE DATE,
RM_START_DATE DATE,
LAST_UPDATE_DATE DATE,
CLASS VARCHAR2(1),
GEOMETRY MDSYS.SDO_GEOMETRY
) TABLESPACE <tablespace name>;

-- Update USER_SDO_GEOM_METADATA
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'AddressBase';
INSERT INTO USER_SDO_GEOM_METADATA VALUES('AddressBase','GEOMETRY',
MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',0,750000,0.001),MDSYS.SDO_DIM_ELEMENT('Y',0,1350000,0.001)),27700);

