#-------------------------------------------------------------------------------
# Name:        `AddressBase Plus and AddressBase Plus Islands Table Creation for Oracle
# Purpose:     `This SQL code is to be used along side the Getting Started Guide
#				to setup the OS AddressBase Premium tables within a database
# Created:     `19/02/2016
# Copyright:   `(c) Ordnance Survey 2016
# Licence:     `THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#               "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#               LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#               FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#               COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#               INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#               BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
#               OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
#               AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#               OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
#               THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE
#-------------------------------------------------------------------------------

---------------------------------------------------------------------------------
--please note you will need to change the <tablespace name> text below with the
--appropriate information for your use--
--please also note some column names have been altered to meet oracle resrictions--
---------------------------------------------------------------------------------

-- Drop Existing Table if exists
DROP TABLE <INSERT TABLE NAME> CASCADE CONSTRAINTS;

-- Create Table for AddressBase Plus
CREATE TABLE <INSERT TABLE NAME> (
UPRN NUMBER,
UDPRN NUMBER,
CHANGE_TYPE VARCHAR2(1),
STATE NUMBER,
STATE_DATE DATE,
CLASS VARCHAR2(6),
PARENT_UPRN NUMBER,
X_COORDINATE FLOAT,
Y_COORDINATE FLOAT,
LATITUDE FLOAT,
LONGITUDE FLOAT,
RPC NUMBER,
LOCAL_CUSTODIAN_CODE NUMBER,
COUNTRY VARCHAR2(1),
LA_START_DATE DATE,
LAST_UPDATE_DATE DATE,
ENTRY_DATE DATE,
RM_ORGANISATION_NAME VARCHAR2(60),
LA_ORGANISATION VARCHAR2(100),
DEPARTMENT_NAME VARCHAR2(60),
LEGAL_NAME VARCHAR2(60),
SUB_BUILDING_NAME VARCHAR2(30),
BUILDING_NAME VARCHAR2(50),
SAO_START_NUMBER NUMBER,
SAO_START_SUFFIX VARCHAR2(2),
SAO_END_NUMBER NUMBER,
SAO_END_SUFFIX VARCHAR2(2),
SAO_TEXT VARCHAR2(90),
ALT_LANGUAGE_SAO_TEXT VARCHAR2(90),
PAO_START_NUMBER NUMBER,
PAO_START_SUFFIX VARCHAR2(2),
PAO_END_NUMBER NUMBER,
PAO_END_SUFFIX VARCHAR2(2),
PAO_TEXT VARCHAR2(90),
ALT_LANGUAGE_PAO_TEXT VARCHAR2(90),
USRN NUMBER,
USRN_MATCH_INDICATOR VARCHAR2(1),
AREA_NAME VARCHAR2(40),
LEVEL_FIELD VARCHAR2(30),
OFFICIAL_FLAG VARCHAR2(1),
OS_ADDRESS_TOID VARCHAR2(20),
OS_ADDRESS_TOID_VERSION NUMBER,
OS_ROADLINK_TOID VARCHAR2(20),
OS_ROADLINK_TOID_VERSION NUMBER,
OS_TOPO_TOID VARCHAR2(20),
OS_TOPO_TOID_VERSION NUMBER,
VOA_CT_RECORD NUMBER,
VOA_NDR_RECORD NUMBER,
STREET_DESCRIPTION VARCHAR2(101),
ALT_LANGUAGE_STREET_DESCRIPTOR VARCHAR2(110),
DEP_THOROUGHFARE VARCHAR2(80),
THOROUGHFARE VARCHAR2(80),
WELSH_DEP_THOROUGHFARE VARCHAR2(80),
WELSH_THOROUGHFARE VARCHAR2(80),
DOU_DEP_LOCALITY VARCHAR2(35),
DEP_LOCALITY VARCHAR2(35),
LOCALITY VARCHAR2(35),
WELSH_DEP_LOCALITY VARCHAR2(35),
WELSH_DOU_DEP_LOCALITY VARCHAR2(35),
TOWN_NAME VARCHAR2(30),
ADMINISTRATIVE_AREA VARCHAR2(30),
POST_TOWN VARCHAR2(35),
WELSH_POST_TOWN VARCHAR2(30),
POSTCODE VARCHAR2(8),
POSTCODE_LOCATOR VARCHAR2(8),
POSTCODE_TYPE VARCHAR2(1),
DELIVERY_POINT_SUFFIX VARCHAR2(2),
ADDRESSBASE_POSTAL VARCHAR2(1),
PO_BOX_NUMBER VARCHAR2(6),
WARD_CODE VARCHAR2(9),
PARISH_CODE VARCHAR2(9),
RM_START_DATE DATE,
MULTI_OCC_COUNT NUMBER,
VOA_NDR_P_DESC_CODE VARCHAR2(5),
VOA_NDR_SCAT_CODE VARCHAR2(4),
ALT_LANGUAGE VARCHAR2(3),
GEOMETRY MDSYS.SDO_GEOMETRY
) TABLESPACE <tablespace name>;


-- Update USER_SDO_GEOM_METADATA
--Please note if you are creating your table for AddressBase Plus Islands you may wish to create
--the USER_SDO_GEOM_METADATA for the appropriate SRID and grid values--
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = '<INSERT TABLE NAME>';
INSERT INTO USER_SDO_GEOM_METADATA VALUES('<INSERT TABLE NAME>','GEOMETRY',
MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',0,750000,0.001),MDSYS.SDO_DIM_ELEMENT('X',0,1350000,0.001)),27700);

